// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: item
func (_m *Validator) Validate(item interface{}) error {
	args := _m.Called(item)
	var r0 error
	if rf, ok := args.Get(0).(func(interface{}) error); ok {
		r0 = rf(item) // validate.Validate(item) get method (Validate) to rf
	} else {
		r0 = args.Error(0)
	}
	return r0
}
